apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
spec:
  replicas: {{ .Values.replicaCount }}
  progressDeadlineSeconds: {{ .Values.progressDeadlineSeconds }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - image: "{{.Values.image.repository}}:{{.Values.image.tag}}"
        name: guestbook
        ports:
        - containerPort: 80
