apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/blakepettersson/kargoring.git
        revision: main
        files:
          - path: "config/*.yaml"
  template:
    metadata:
      name: 'kargo-{{.appName}}'
    spec:
      project: kargo-demo
      source:
        repoURL: https://github.com/blakepettersson/kargo-boilerplate.git
        path: .
        helm:
          valuesObject:
            nameOverride: '{{.appName}}'
            warehouse:
              subscriptions:
                - chart:
                    repoURL: '{{.repoUrl}}/{{.chart}}'
                    semverConstraint: '*'
                - image:
                    repoURL: '{{.image}}'
                    semverConstraint: '*'
            stages:
              - name: dev
                annotations:
                  kargo.akuity.io/color: purple
                subscriptions:
                  warehouse: '{{.appName}}'
                promotionMechanisms:
                  argoCDAppUpdates:
                    - appName: '{{.appName}}-dev'
                      sourceUpdates:
                        - repoURL: '{{.repoUrl}}'
                          chart: '{{.chart}}'
                          helm:
                            images:
                              - image: '{{.image}}'
                                key: image.tag
                                value: Tag # Update Application to reference the new image version
                          updateTargetRevision: true # Update Application to reference the new chart version
      destination:
        name: kargo1
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true
