# This manages the Kargo manifests (see kargo directory)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-guestbook
spec:
  project: kargo-demo
  source:
    repoURL: https://github.com/blakepettersson/kargoring.git
    path: kargo
  destination:
    name: kargo1
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
