apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-guestbook
spec:
  project: kargo-demo
  source:
    repoURL: https://github.com/blakepettersson/kargoring.git
    path: kargo
  destination:
    name: kargo1
    #server: https://f77el9953au135eb-cplane.kargosvcs.akuity.cloud
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
