apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: stages
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          # list generator, 'child' #1
          - list:
              elements:
                - appName: guestbook
          # cluster generator, 'child' #2
          - clusters:
              selector:
                matchLabels:
                  kargo-demo: 'true'
  template:
    metadata:
      name: '{{.appName}}-{{.name}}'
      annotations:
        kargo.akuity.io/authorized-stage: '{{.appName}}:{{.name}}'
    spec:
      project: kargo-demo
      source:
        repoURL: https://github.com/blakepettersson/guestbook.git
        targetRevision: 'stage/{{.name}}'
        helm:
          valuesObject:
            dnsZone: '{{ index .metadata.annotations "dns-zone" }}'
          valueFiles:
            - 'values-{{.name}}.yaml'
          releaseName: '{{.appName}}'
        path: .
      destination:
        name: '{{.name}}'
        namespace: '{{.appName}}'
      # Autosync NOT enabled for application stages, since the syncing is managed via Kargo.
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
