apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: stages
  namespace: argocd
spec:
  ignoreApplicationDifferences:
    - jqPathExpressions:
        - .spec.source.targetRevision
        - .spec.source.helm.parameters
  goTemplate: true
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/blakepettersson/kargoring.git
              revision: test
              files:
                - path: "config/*.yaml"
          # cluster generator, 'child' #2
          - clusters: {}
  template:
    metadata:
      name: '{{.appName}}-dev'
      annotations:
        kargo.akuity.io/authorized-stage: '{{.appName}}:dev'
    spec:
      project: kargo-demo
      source:
        repoURL: '{{.registry | trimPrefix "oci://" }}'
        chart: '{{.chart}}'
        # Kargo will update targetRevision to move new charts into each stage
        targetRevision: 0.1.0 # Initial value needs to exist in remote repo, subsequent revisions will be handled by Kargo.
        helm:
          valueFiles:
            - 'values-dev.yaml' # This is a values file that is _baked into_ the OCI Helm chart.
      destination:
        name: '{{.name}}'
        namespace: '{{.appName}}'
      # Autosync NOT enabled for application stages, since the syncing is managed via Kargo.
      syncPolicy:
        syncOptions:
          - CreateNamespace=true